[package]
name = "export-to-unity-dynamic-binder"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.100", features = ["full", "visit"] }
quote = "1.0"
anyhow = "1.0"
proc-macro2 = "1.0.94"
phf = { version = "0.11.3", features = ["macros"] }